name: Linters

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  call:
    uses: opiproject/actions/.github/workflows/linters.yml@main
    secrets: inherit
